[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

# Asegura que /admin cargue el index del panel
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Cache fuerte para assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
