backend:
  name: git-gateway
  branch: main
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    file: "data/noticias.json"
    format: "json"
    fields:
      - { label: "Título",  name: "titulo",  widget: "string" }
      - { label: "Resumen", name: "resumen", widget: "text", required: false }
      - { label: "Cuerpo",  name: "cuerpo",  widget: "text", required: false }
      - { label: "Imagen",  name: "imagen",  widget: "image", required: false }
      - { label: "Fecha",   name: "fecha",   widget: "datetime", format: "YYYY-MM-DD" }
