backend:
  name: git-gateway
  branch: main   # o "principal" si tu repo usa ese nombre

media_folder: "assets/images"     # dónde guarda las imágenes en el repo
public_folder: "/assets/images"   # cómo se referencian en la web

collections:
  - name: "noticias"
    label: "Noticias (Inicio)"
    files:
      - file: "data/noticias.json"
        label: "Listado de noticias"
        name: "listado"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Título",  name: "titulo",  widget: "string" }
              - { label: "Resumen", name: "resumen", widget: "text", required: false }
              - { label: "Imagen",  name: "imagen",  widget: "image", required: false }
              - { label: "Cuerpo",  name: "cuerpo",  widget: "markdown" }
              - { label: "Fecha",   name: "fecha",   widget: "datetime", format: "YYYY-MM-DD" }
