backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: editorial_workflow

collections:
  - name: "noticias"
    label: "Noticias"
    files:
      - file: "data/noticias.json"
        name: "listado"
        label: "Listado de noticias"
        fields:
          - label: "Noticias"
            name: "items"
            widget: "list"
            summary: "{{fields.titulo}} — {{fields.fecha}}"
            fields:
              - { label: "Título",  name: "titulo",  widget: "string" }
              - { label: "Fecha",   name: "fecha",   widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "Resumen", name: "resumen", widget: "text" }
              - { label: "Imagen",  name: "imagen",  widget: "image" }
              - { label: "Cuerpo",  name: "cuerpo",  widget: "markdown" }
